Affirmation.create!([
  {category: "Self-fulfillment and Freedom", affirmation: "My dreams are manifesting before my eyes"},
  {category: "Self-fulfillment and Freedom", affirmation: "My potential to succeed is infinite"},
  {category: "Self-fulfillment and Freedom", affirmation: "I am worthy of everything I desire"},
  {category: "Self-fulfillment and Freedom", affirmation: "I have the power to change my life by changing my thoughts"},
  {category: "Self-fulfillment and Freedom", affirmation: "I love where I am in life"},
  {category: "Self-fulfillment and Freedom", affirmation: "I set high goals and achieve them"},
  {category: "Self-fulfillment and Freedom", affirmation: "I am living on my own terms"},
  {category: "Self-fulfillment and Freedom", affirmation: "I say thank you for each blessing in my life"},
  {category: "Self-fulfillment and Freedom", affirmation: "My abundant life is full of beauty and wisdom"},
  {category: "Self-fulfillment and Freedom", affirmation: "I am traveling and exploring the world"},
  {category: "Self-fulfillment and Freedom", affirmation: "I pursue my passion and let my creativity spark"},
  {category: "Money and Prosperity", affirmation: "I love feeling financially secure"},
  {category: "Money and Prosperity", affirmation: "No matter what I will succeed"},
  {category: "Money and Prosperity", affirmation: "I choose to create all this or something better"},
  {category: "Money and Prosperity", affirmation: "I am worthy of being wealthy"},
  {category: "Money and Prosperity", affirmation: "I am financially abundant "},
  {category: "Money and Prosperity", affirmation: "I have enough wealth to provide for myself and my loved ones"},
  {category: "Money and Prosperity", affirmation: "My potential to succeed is infinite"},
  {category: "Money and Prosperity", affirmation: "I love and respect money"},
  {category: "Money and Prosperity", affirmation: "I am worthy of everything I desire"},
  {category: "Money and Prosperity", affirmation: "I have the power to attract money"},
  {category: "Money and Prosperity", affirmation: "I receive and give money happily"},
  {category: "Money and Prosperity", affirmation: "The universe takes good care of me"},
  {category: "Money and Prosperity", affirmation: "I always live in comfort and joy"},
  {category: "Money and Prosperity", affirmation: "Abundance surrounds me"},
  {category: "Money and Prosperity", affirmation: "I have unlimited potential to succeed"},
  {category: "Money and Prosperity", affirmation: "I am happy to share my abundance"},
  {category: "Money and Prosperity", affirmation: "Money flows to me in unexpected ways"},
  {category: "Money and Prosperity", affirmation: "I can accomplish anything I set my mind to"},
  {category: "Money and Prosperity", affirmation: "I always have more than I need"},
  {category: "Money and Prosperity", affirmation: "I love money and money loves me"},
  {category: "Money and Prosperity", affirmation: "My income is constantly expanding"},
  {category: "Money and Prosperity", affirmation: "I am a money magnet"},
  {category: "Money and Prosperity", affirmation: "Attracting money is easy for me"},
  {category: "Money and Prosperity", affirmation: "I have a successful wealth mindset"},
  {category: "Money and Prosperity", affirmation: "I easily pay my bills"},
  {category: "Money and Prosperity", affirmation: "Money is constantly flowing into my life"},
  {category: "Money and Prosperity", affirmation: "I always have enough money to fulfill my needs and reach my dreams"},
  {category: "Love and Relationships", affirmation: "I attract healthy relationships into my life"},
  {category: "Love and Relationships", affirmation: "I love myself"},
  {category: "Love and Relationships", affirmation: "I will attract the perfect partner into my life"},
  {category: "Love and Relationships", affirmation: "Love is coming to me now"},
  {category: "Love and Relationships", affirmation: "All my relationships are now harmonious"},
  {category: "Love and Relationships", affirmation: "My ideal partner is coming my way"},
  {category: "Love and Relationships", affirmation: "I have an attractive personality"},
  {category: "Love and Relationships", affirmation: "I make friends easily, wherever I go"},
  {category: "Love and Relationships", affirmation: "I love and accept myself the way I do to others"},
  {category: "Love and Relationships", affirmation: "I am worthy of being loved"},
  {category: "Love and Relationships", affirmation: "My life is full of loving and uplifting people"},
  {category: "Love and Relationships", affirmation: "I am kind and generous in my relationships"},
  {category: "Love and Relationships", affirmation: "My life is filled with joy and abundance"},
  {category: "Love and Relationships", affirmation: "I have the power to change my life by changing my thoughts"},
  {category: "Love and Relationships", affirmation: "I have the courage to follow my heart and pursue my passion"},
  {category: "Love and Relationships", affirmation: "My passion ignites the fire inside of me"},
  {category: "Love and Relationships", affirmation: "I am the perfect partner for my perfect partner"},
  {category: "Love and Relationships", affirmation: "I can achieve my dreams"},
  {category: "Love and Relationships", affirmation: "I am eternally grateful for all that I have"},
  {category: "Love and Relationships", affirmation: "The universe takes good care of me"},
  {category: "Love and Relationships", affirmation: "I have the power to create my reality"},
  {category: "Safe and Secure", affirmation: "I am outwardly focused"},
  {category: "Safe and Secure", affirmation: "I own who I am"},
  {category: "Safe and Secure", affirmation: "I believe in my truth"},
  {category: "Safe and Secure", affirmation: "I listen to my intuition"},
  {category: "Safe and Secure", affirmation: "I know that all is well"},
  {category: "Safe and Secure", affirmation: "I am purposeful in life"},
  {category: "Safe and Secure", affirmation: "I am decisive"},
  {category: "Safe and Secure", affirmation: "My life has importance"},
  {category: "Safe and Secure", affirmation: "I am steady and whole"},
  {category: "Safe and Secure", affirmation: "I am impowered"},
  {category: "Safe and Secure", affirmation: "I am grounded"},
  {category: "Safe and Secure", affirmation: "I am connected to mother earth"},
  {category: "Safe and Secure", affirmation: "I am healed"},
  {category: "Safe and Secure", affirmation: "I am balanced"},
  {category: "Safe and Secure", affirmation: "I am complete"},
  {category: "Safe and Secure", affirmation: "I trust my self"},
  {category: "Safe and Secure", affirmation: "My peace is active"},
  {category: "Safe and Secure", affirmation: "I am energetic"},
  {category: "Health and well-being", affirmation: "I can do it"},
  {category: "Health and well-being", affirmation: "I have blind faith in my success"},
  {category: "Health and well-being", affirmation: "I am persistent in creating better health for my self"},
  {category: "Health and well-being", affirmation: "I take care of my body"},
  {category: "Health and well-being", affirmation: "I know and respect my body "},
  {category: "Health and well-being", affirmation: "I stay connected to my soul every day"},
  {category: "Health and well-being", affirmation: "I feel love thinking about myself"},
  {category: "Health and well-being", affirmation: "I am worthy of good health"},
  {category: "Health and well-being", affirmation: "I nourish my body with healthy foods"},
  {category: "Health and well-being", affirmation: "I listen to my body and it gives me the answers"},
  {category: "Health and well-being", affirmation: "I am taking small steps every day to become healthy"},
  {category: "Health and well-being", affirmation: "I am always honest with myself"},
  {category: "Health and well-being", affirmation: "I have the power to activate a better me"},
  {category: "Health and well-being", affirmation: "I have a clear goal and I follow it consistently"},
  {category: "Health and well-being", affirmation: "Being healthy is my state of mind"},
  {category: "Health and well-being", affirmation: "I support my body on this journey to heal"},
  {category: "Health and well-being", affirmation: "I keep my mind open to new possibilities"},
  {category: "Health and well-being", affirmation: "I keep calm knowing I am always safe"},
  {category: "Health and well-being", affirmation: "My body always tells me what it needs"},
  {category: "Health and well-being", affirmation: "Staying alert helps me find new solutions"},
  {category: "Health and well-being", affirmation: "I do the best I can to be better"},
  {category: "Health and well-being", affirmation: "I plant the seed of good health and help it grow"},
  {category: "Health and well-being", affirmation: "I breath more freely everyday"},
  {category: "Health and well-being", affirmation: "Whatever happens – I will succeed"},
  {category: "Abundance", affirmation: "I am grateful for everything that I have"},
  {category: "Abundance", affirmation: "I have everything I need in life."},
  {category: "Abundance", affirmation: "I deserve everything I want."},
  {category: "Abundance", affirmation: "I am wealthy and prosperous."},
  {category: "Abundance", affirmation: "I am a magnet for success."},
  {category: "Abundance", affirmation: "Each day of my life is filled with abundance."},
  {category: "Abundance", affirmation: "I am grateful for the amount of abundance I have."},
  {category: "Abundance", affirmation: "I am attracting money and wealth into my environment."},
  {category: "Abundance", affirmation: "I have enough of everything I need."},
  {category: "Abundance", affirmation: "Prosperity flows through every aspect of my life."},
  {category: "Abundance", affirmation: "The universe will provide for me."},
  {category: "Abundance", affirmation: "I attract an abundance of wealth and opportunity."},
  {category: "Abundance", affirmation: "Every part of my life is filled with prosperity."}
])
